# References:
#  - https://esphome.io/components/audio_dac/es8388/#configuration-examples
#  - https://github.com/sle118/squeezelite-esp32#esp32-a1s

defaults:
  speaker_id: speaker_id
  mic_id: mic_id

esphome:
  comment: ESP32 Audio Kit (v2.2)

packages:
  - !include
    file: ../esp32-a1s/esp32-a1s-es8388.yaml
    vars:
      speaker_id: ${speaker_id}
      mic_id: ${mic_id}

switch:
  - id: mute_switch
    platform: gpio
    pin: GPIO21
    name: "AMP Switch"
    restore_mode: ALWAYS_ON
    entity_category: config

binary_sensor:
  - id: sensor_jack
    platform: gpio
    pin:
      number: GPIO39
      inverted: true
      mode:
        input: true
    name: "Jack"
    filters: # needs debouncing
      - delayed_on: 200ms
      - delayed_off: 200ms
    entity_category: diagnostic
    # TODO: Switch esp8266_dac_output and mute_switch based on sensor_jack?

  # Note that GPIO0 is used by the I2S bus

  - id: key_1
    platform: gpio
    pin:
      number: GPIO36
      inverted: true
    name: "Key 1"
    filters:
      - delayed_off: 10ms
  - id: key_2
    platform: gpio
    pin:
      number: GPIO13
      inverted: true
    name: "Key 2"
    filters:
      - delayed_off: 10ms
  - id: key_3
    platform: gpio
    pin:
      number: GPIO19
      inverted: true
    name: "Key 3"
    filters:
      - delayed_off: 10ms
    # Also connected to bottom LED
  - id: key_4
    platform: gpio
    pin:
      number: GPIO23
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 4"
    filters:
      - delayed_off: 10ms
  - id: key_5
    platform: gpio
    pin:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 5"
    filters:
      - delayed_off: 10ms
  - id: key_6
    platform: gpio
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
      ignore_strapping_warning: true
    name: "Key 6"
    filters:
      - delayed_off: 10ms

output:
  - # Top LED
    id: out_builtin
    platform: ledc
    pin:
      number: GPIO22
      inverted: true
    frequency: 1000 Hz
  # Bottom LED is shared with Key 3

light:
  - # Top LED - called "Green" in squeezelite-esp32 config
    id: led_builtin
    platform: monochromatic
    output: out_builtin
    name: Status
    restore_mode: ALWAYS_OFF
    entity_category: config
