# ESP32 Cheap Yellow Display (original)
# See:
# - https://mischianti.org/esp32-2432s028-cheap-yellow-display-high-resolution-pinout-datasheet-schema-and-specs/

esphome:
  comment: ESP32 Cheap Yellow Display

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  - !include
    file: ../../packages/display/auto_dimming.yaml
    vars:
      light_sensor_id: light_level_raw
      light_id: backlight
      light_name: Backlight

# SPI bus
spi:
  - id: bus_lcd
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true # built-in
  - id: bus_touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39

# Button
binary_sensor:
  - id: btn_boot
    platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true # built-in
    name: "Boot"
    entity_category: diagnostic

# Sensor
sensor:
  - id: adc_ldr_raw
    platform: adc
    pin: 34
    attenuation: auto
    name: "ADC Voltage Raw"
    state_class: measurement
    update_interval: 1s
    disabled_by_default: true
  - id: light_level_raw
    platform: template
    name: "Light Level Raw"
    lambda: "return max(1.0 - id(adc_ldr_raw).state / 3.0, 0.0);"
    unit_of_measurement: ""
    accuracy_decimals: 3
    device_class: ""
    icon: mdi:brightness-5
    state_class: measurement
    update_interval: 1s
    disabled_by_default: true

display:
  - # 320x240
    id: display_lcd
    platform: mipi_spi
    model: ili9341 # or ESP32-2432S028
    spi_id: bus_lcd
    data_rate: 40MHz
    cs_pin:
      number: 15
      ignore_strapping_warning: true # built-in
    dc_pin:
      number: 2
      ignore_strapping_warning: true # built-in
    buffer_size: 50%
    update_interval: 1s

touchscreen:
  - id: touch_lcd
    platform: xpt2046
    display: display_lcd
    spi_id: bus_touch
    cs_pin: 33
    interrupt_pin: 36
    update_interval: 50ms
    threshold: 400
    calibration:
      x_min: 300
      x_max: 4000
      y_min: 300
      y_max: 4000

output:
  - id: lcd_backlight_pwm
    platform: ledc
    pin: 21
  - id: led_r
    platform: ledc
    pin: 4
    inverted: true
    phase_angle: 90
  - id: led_g
    platform: ledc
    pin: 16
    inverted: true
    phase_angle: 180
  - id: led_b
    platform: ledc
    pin: 17
    inverted: true
    phase_angle: 270

light:
  - id: backlight
    platform: monochromatic
    output: lcd_backlight_pwm
    name: "Backlight"
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
  - id: led_builtin
    platform: rgb
    name: "Status"
    red: led_r
    green: led_g
    blue: led_b
    restore_mode: ALWAYS_OFF
    entity_category: config
