# Based on https://github.com/iMicknl/LoctekMotion_IoT/blob/main/packages/office-desk-esp32.yaml
defaults:
  source_loctekmotion: github://iMicknl/LoctekMotion_IoT@main
  tx_pin: GPIO21
  rx_pin: GPIO20
  screen_pin: GPIO10
  min_height: "58.1" # Min height + 0.1
  max_height: "122.9" # Max height - 0.1

external_components:
  - source: ${source_loctekmotion}
    components: [loctekmotion_desk_height]

esphome:
  # Delay UART interaction on boot to give the desk controller time to initialize.
  # After the delay, wake the desk by sending the "M" command to request the current height.
  on_boot:
    - priority: -100
      then:
        - delay: 10s
        - button.press: button_wake_screen
        - delay: 300ms
        - button.press: button_m

uart:
  - id: desk_uart
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

sensor:
  - id: desk_height
    platform: loctekmotion_desk_height
    name: Desk Height
    on_value_range:
      - below: ${min_height}
        then:
          - switch.turn_off: switch_down
          - button.press: button_wake_screen
      - above: ${max_height}
        then:
          - switch.turn_off: switch_up
          - button.press: button_wake_screen
    on_value:
      then:
        - cover.template.publish:
            id: desk_cover
            position: !lambda |-
              // The sensor outputs values from min_height (cm) to max_height (cm)
              // We need to translate this to 0 - 1 scale.
              float position = (float(x) - float(${min_height})) / (float(${max_height}) - float(${min_height}));
              return position;
        - component.update: set_desk_height

switch:
  - id: switch_screen
    platform: gpio
    name: "Virtual Screen"
    pin:
      number: ${screen_pin}
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    entity_category: "config"
    internal: true

  - id: switch_up
    platform: uart
    name: "Up"
    icon: mdi:arrow-up-bold
    data: [0x9b, 0x06, 0x02, 0x01, 0x00, 0xfc, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true
    on_turn_on:
      - button.press: button_wake_screen
      - delay: 200ms

  - id: switch_down
    platform: uart
    name: "Down"
    icon: mdi:arrow-down-bold
    data: [0x9b, 0x06, 0x02, 0x02, 0x00, 0x0c, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true
    on_turn_on:
      - button.press: button_wake_screen
      - delay: 200ms

  - id: switch_alarm
    platform: uart
    name: "Alarm Off"
    icon: mdi:alarm
    data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xAC, 0x90, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    on_turn_on:
      - delay: 3000ms
      - switch.turn_off: switch_alarm
    entity_category: "config"

  - id: switch_child_lock
    platform: uart
    name: "Child Lock"
    icon: mdi:account-lock
    data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    on_turn_on:
      - delay: 5000ms
      - switch.turn_off: switch_child_lock
    entity_category: "config"

button:
  - id: preset_1
    platform: template
    name: "Preset 1"
    icon: mdi:numeric-1-box
    on_press:
      - button.press: button_wake_screen
      - delay: 200ms
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]

  - id: preset_2
    platform: template
    name: "Preset 2"
    icon: mdi:numeric-2-box
    on_press:
      - button.press: button_wake_screen
      - delay: 200ms
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]

  - id: preset_3
    platform: template
    name: "Sit" # Preset 3 on some control panels
    icon: mdi:chair-rolling
    on_press:
      - button.press: button_wake_screen
      - delay: 200ms
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x00, 0x01, 0xac, 0x60, 0x9d]

  - id: preset_4
    platform: template
    name: "Stand" # Preset 4 on some control panels
    icon: mdi:human-handsup
    on_press:
      - button.press: button_wake_screen
      - delay: 200ms
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]

  - id: button_m
    platform: template
    name: "Memory"
    icon: mdi:alpha-m-box
    entity_category: "config"
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]

  - id: button_wake_screen
    platform: template
    name: "Wake Screen"
    icon: mdi:gesture-tap-button
    entity_category: "config"
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x00, 0x00, 0x6c, 0xa1, 0x9d]

  - id: button_alarm
    platform: template
    name: "Alarm"
    icon: mdi:alarm
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xAC, 0x90, 0x9d]

cover:
  - id: desk_cover
    platform: template
    icon: mdi:desk # or mdi:human-male-height-variant
    name: "Desk"
    device_class: blind # makes it easier to integrate with Google/Alexa
    has_position: true
    position_action:
      - if:
          condition:
            - lambda: !lambda |-
                return pos > id(desk_cover).position;
          then:
            - cover.open: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_cover).position  >= pos;
            - cover.stop: desk_cover
          else:
            - cover.close: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_cover).position <= pos;
            - cover.stop: desk_cover
    stop_action:
      - switch.turn_off: switch_up
      - switch.turn_off: switch_down
      - button.press: button_wake_screen
    open_action:
      - switch.turn_off: switch_down
      - switch.turn_on: switch_up
    close_action:
      - switch.turn_off: switch_up
      - switch.turn_on: switch_down
    optimistic: false

number:
  - id: set_desk_height
    platform: template
    name: "Desk Height"
    min_value: ${min_height}
    max_value: ${max_height}
    icon: "mdi:counter"
    unit_of_measurement: "cm"
    device_class: "distance"
    step: 0.1
    lambda: !lambda |-
      return id(desk_height).state;
    set_action:
      - if:
          condition:
            - lambda: !lambda |-
                return x > id(desk_height).state;
          then:
            - cover.open: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_height).state  >= x;
            - cover.stop: desk_cover
          else:
            - cover.close: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_height).state <= x;
            - cover.stop: desk_cover
