# https://www.waveshare.com/wiki/ESP32-C3-Zero
# Chip is (usually) ESP32-C3FN4

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

# UART connected to RX/TX pins
uart:
  - id: bus_uart0
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 115200

# Lights
light:
  - id: led_builtin
    platform: esp32_rmt_led_strip
    name: "Status"
    rgb_order: GRB
    pin: GPIO10
    num_leds: 1
    chipset: ws2812
    restore_mode: ALWAYS_OFF
    entity_category: config

# Buttons
binary_sensor:
  - id: btn_boot
    platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true
    name: "Boot"
    filters:
      - delayed_off: 10ms # debounce
    entity_category: diagnostic
