# Based on https://github.com/esphome/bluetooth-proxies/blob/main/esp32-generic/esp32-generic-c3.yaml
defaults:
  connection_slots: 3

packages:
  - !include
    file: base.yaml
    vars:
      connection_slots: ${connection_slots}

esphome:
  comment: Bluetooth Proxy (esp32-c3)

esp32:
  variant: esp32c3
  framework:
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n
