substitutions:
  pin_builtin_led: GPIO8
  pin_boot: GPIO9

esp32:
  variant: esp32c3
  framework: esp-idf

esphome:
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

# Outputs
output:
  - platform: ledc
    pin:
      number: ${pin_builtin_led}
      inverted: true
      ignore_strapping_warning: true
    frequency: 1000 Hz
    id: out_builtin

# Lights
light:
  - platform: monochromatic
    output: out_builtin
    name: "Status"
    id: led_builtin
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

# Buttons
binary_sensor:
  - platform: gpio
    pin:
      number: ${pin_boot}
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true
    id: btn_boot
    name: "Boot"
    filters:
      - delayed_off: 10ms # debounce
