# Shared WiFi with sensors
wifi:
  id: wifi_id

sensor:
  - id: sensor_wifi_signal
    platform: wifi_signal
    name: Wi-Fi signal
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      id: sensor_wifi_ip
      name: Wi-Fi IP address
      internal: true
    ssid:
      id: sensor_wifi_ssid
      name: Wi-Fi SSID
      internal: true
