# Examples
#  - https://esphome.io/components/media_player/speaker/
#  - https://github.com/esphome/home-assistant-voice-pe/blob/25.11.0/home-assistant-voice.yaml

defaults:
  speaker_id: speaker_id
  num_channels: 2
  task_stack_in_psram: false

speaker:
  # Virtual speakers to combine the announcement and media streams together into one output
  - id: mixing_speaker
    platform: mixer
    output_speaker: ${speaker_id}
    num_channels: ${num_channels}
    task_stack_in_psram: ${task_stack_in_psram}
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never

  # Virtual speakers to resample each pipeline's audio, if necessary, as the mixer speaker requires the same sample rate
  - id: announcement_resampling_speaker
    platform: resampler
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

  - id: media_resampling_speaker
    platform: resampler
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
