# Examples
#  - https://esphome.io/components/media_player/speaker_source/
#  - https://github.com/esphome/home-assistant-voice-pe/pull/562
#  - https://github.com/esphome/home-assistant-voice-pe/blob/26.2.2/home-assistant-voice.yaml
#  - https://github.com/sonocotta/esp32-audio-dock/blob/main/firmware/esphome/packages/sendspin.yaml

defaults:
  speaker_id: external_speaker
  media_player_id: external_media_player
  num_channels: 2
  task_stack_in_psram: false

esphome:
  min_version: 2026.3.0

packages:
  - !include
    file: classic.yaml
    vars:
      speaker_id: ${speaker_id}
      media_player_id: ${media_player_id}
      num_channels: ${num_channels}
      task_stack_in_psram: ${task_stack_in_psram}

# Sendspin related components are pinned to specific commits for reproducible builds
external_components:
  - source:
      # https://github.com/esphome/esphome/pull/14933
      type: git
      url: https://github.com/kahrendt/esphome
      ref: 890e33f99af2c2ea15dc74c3ec4cf32d25203526
    components: [const, media_source, sendspin]
  - source:
      # https://github.com/esphome/esphome/pull/12429
      type: git
      url: https://github.com/esphome/esphome
      ref: ff8ce89556748509d7ee8724e12d9d43d3c8c1e8
    components: [http_request]

sendspin: # from PR
  id: sendspin_hub
  task_stack_in_psram: false # ${task_stack_in_psram}

http_request: # from PR
  buffer_size_rx: 2048 # Reduces CPU load when streaming audio

audio_file: # from 2026.03

media_source:
  - id: file_announcement_source
    platform: audio_file # from 2026.03
  - id: http_announcement_source
    platform: http_request # from PR
    buffer_size: 250000
  - id: http_media_source
    platform: http_request # from PR
    buffer_size: 500000
  - id: sendspin_media_source
    platform: sendspin # from PR

media_player:
  - id: sendspin_group_media_player
    platform: sendspin # from PR
  - id: !extend ${media_player_id}
    platform: speaker_source # from 2026.03
    task_stack_in_psram: !remove
    announcement_pipeline:
      sources:
        - file_announcement_source
        - http_announcement_source
    media_pipeline:
      sources:
        - http_media_source
        - sendspin_media_source
