# Examples
#  - https://esphome.io/components/media_player/speaker_source/
#  - https://github.com/esphome/home-assistant-voice-pe/pull/562
#  - https://github.com/esphome/home-assistant-voice-pe/blob/26.2.2/home-assistant-voice.yaml
#  - https://github.com/sonocotta/esp32-audio-dock/blob/main/firmware/esphome/packages/sendspin.yaml

defaults:
  speaker_id: external_speaker
  media_player_id: external_media_player
  media_format: FLAC # FLAC is the least processor intensive codec
  num_channels: 2

esphome:
  min_version: 2026.5.0

packages:
  - !include
    file: classic.yaml
    vars:
      speaker_id: ${speaker_id}
      media_player_id: ${media_player_id}
      media_format: ${media_format}
      num_channels: ${num_channels}

sendspin: # from 2026.05
  id: sendspin_hub

audio_file: # from 2026.03

media_source:
  - id: file_announcement_source
    platform: audio_file # from 2026.03
  - id: http_announcement_source
    platform: audio_http # from 2026.05
    buffer_size: 250000
  - id: http_media_source
    platform: audio_http # from 2026.05
    buffer_size: 500000
  - id: sendspin_media_source
    platform: sendspin # from 2026.05

media_player:
  - id: sendspin_group_media_player
    platform: sendspin # from 2026.05
    name: Media Group
  - id: !extend ${media_player_id}
    platform: speaker_source # from 2026.03
    announcement_pipeline:
      sources:
        - file_announcement_source
        - http_announcement_source
    media_pipeline:
      sources:
        - http_media_source
        - sendspin_media_source
