defaults:
  light_sensor_id: null
  light_id: null
  light_name: "Backlight"

script:
  - id: update_brightness
    then:
      - if:
          condition:
            lambda: 'return id(light_mode).current_option() == "auto";'
          then:
            - if:
                condition:
                  lambda: "return id(${light_sensor_id}).state < id(light_threshold).state;"
                then:
                  - light.turn_on:
                      id: ${light_id}
                      brightness: !lambda "return id(light_low).state;"
                else:
                  - light.turn_on:
                      id: ${light_id}
                      brightness: !lambda "return id(light_high).state;"

select:
  - id: light_mode
    platform: template
    name: "${light_name} Mode"
    options:
      - auto
      - manual
    restore_value: true
    optimistic: true
    disabled_by_default: true
    entity_category: config
    on_value:
      then:
        - script.execute: update_brightness

number:
  - id: light_threshold
    platform: template
    name: "${light_name} Threshold"
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.01
    restore_value: true
    initial_value: 0.7
    disabled_by_default: true
    entity_category: config
    on_value:
      then:
        - script.execute: update_brightness
  - id: light_low
    platform: template
    name: "${light_name} Low Brightness"
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.01
    restore_value: true
    initial_value: 0.3
    disabled_by_default: true
    entity_category: config
    on_value:
      then:
        - script.execute: update_brightness
  - id: light_high
    platform: template
    name: "${light_name} High Brightness"
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.01
    restore_value: true
    initial_value: 1
    disabled_by_default: true
    entity_category: config
    on_value:
      then:
        - script.execute: update_brightness

sensor:
  - id: !extend ${light_sensor_id}
    on_value:
      then:
        - script.execute: update_brightness
