# Chip is (usually) ESP32-C3FN4

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

# Outputs
output:
  - id: out_builtin
    platform: ledc
    pin:
      number: GPIO8
      inverted: true
      ignore_strapping_warning: true
    frequency: 1000 Hz

# Lights
light:
  - id: led_builtin
    platform: monochromatic
    output: out_builtin
    name: "Status"
    restore_mode: ALWAYS_OFF
    entity_category: config

# Buttons
binary_sensor:
  - id: btn_boot
    platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true
    name: "Boot"
    filters:
      - delayed_off: 10ms # debounce
    entity_category: diagnostic
